### ISSUE TITLE
nv-codec-headers.git SDK 9.0

### ISSUE THREAD

**Issue by Lenglemetz** [omen23/ffmpeg-ffnvcodec-explanation#2]
Hi,

I saw the new instructions, so I tried the new build of ffmpeg with "no-sign".

But I had a bug, the build of ffmpeg happens normally, the modules are present but it does not work in OBS

So I looked at the side of videolan codecs is the SDK 9.0 that makes the streaming does not launch in OBS, changing branch (back to 8.2) streaming and recording returns, with a new build of ffmpeg of course.

I think you have to indicate it

regard,

**Comment by catb0t** [comment]
what NVIDIA driver version do you have?

**Comment by Lenglemetz** [comment]
i have nvidia-driver-415

**Comment by omen23** [comment]
wait.. wait .. the nvidia headers work with every version of FFmpeg but the
newer headers require a newer driver ...

tbh.. its like dont touch a running system .. when you ffmpeg 4.0.2 running
with OBS 22.0.2 and it works dont touch it until you have to – but I will
look into it ...
also I am having no problem with using -uc -us instead of --no-sign.
-------------------------
FFmpeg version of headers required to interface with Nvidias codec APIs.

Corresponds to Video Codec SDK version 9.0.18.

Minimum required driver versions:
Linux: 418.30 or newer
Windows: 418.81 or newer
-------------------------
you can get a new version from the nvidia homepage but not as .deb but the blob installer ... which isnt as clean as using your systems packaging system .. give them a few days and they will roll out a new version in the gpu ppa...



Am Fr., 15. Feb. 2019 um 20:20 Uhr schrieb Gaëtan L. <
notifications@github.com>:

**Comment by omen23** [comment]
need newer drivers - closed

**Comment by Lenglemetz** [comment]
Hi,

ok, but you forget an instruction .... this command downloads the sdk 9.0 by default, you have to change branch to be in sdk 8.2 :

git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git

**Comment by omen23** [comment]
it always should be the newest SDK,
when I wrote it SDK 8.2 was the newest .. cant update this manual all the
time.

Regards

Am So., 17. Feb. 2019 um 17:23 Uhr schrieb Gaëtan L. <
notifications@github.com>:

**Comment by omen23** [comment]
git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git will get you the SDK 9.0 atleast at the time of writing (18-2-2019) – you see there are multiple projects (all getting updated at different paces – I cant fix this up all the time)  – just roll it with SDK 9.0 and download the nvidia binary installer .. if you want to use the new SDK!

**Comment by Lenglemetz** [comment]
Hi,

I just saw the addition of "git checkout n8.2.15.7 # for drivers of 415.x and more", it's cool, you finally understood the initial request ;-)

**Comment by omen23** [comment]
Hey,
I'd be really thankful if you donated a few euros. Thank you in advance.

"Donations
 If this manual helped you out in any way and you wanna support me by buying a cup of coffee or a little 
 something donate here."
https://github.com/omen23/ffmpeg-ffnvcodec-explanation#donations

Greetings

ps.: why are US people willing to donate and Europeans still think its free as in free beer – if nothing comes back I can't write future "how-to's" and if nothing comes back I won't too – I am not asking for much but idk ... people should be more appreciative a technician coming to your home is easy € 30 just for coming and then € 60 per hr (if not more).
This is the only working guide to roll FFmpeg and make libavcodec export h264_nvenc on the internet and make OBS work with NVENC.
 
Am Mo., 18. Feb. 2019 um 10:41 Uhr schrieb Gaëtan L. <
notifications@github.com>:

**Comment by Lenglemetz** [comment]
Oo ...
